JobLandin.Web/Controllers/CandidateController.cs
using JobLandin.Application.Common.Interfaces;
using JobLandin.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace JobLandin.Web.Controllers
{
    public class CandidateController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CandidateController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var candidates = _unitOfWork.Candidate.GetAll();
            return View(candidates);
        }



        //GET
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Candidate obj)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //ProfilePic File Upload
                    if (obj.Image is not  null)
                    {
                        Console.WriteLine("ProfilePic Image is not null, proceeding with file upload."); // Logging

                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                        string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\CandidateProfilePics");
                        using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                        obj.Image.CopyTo(fileStream);

                        obj.ProfilePicUrl = @"\images\CandidateProfilePics\" + fileName;
                        
                    }
                    else
                    {
                        Console.WriteLine("ProfilePic Image is null, using default ProfilePic logo URL."); // Logging
                        obj.ProfilePicUrl = "https://placehold.co/50x50";
                    }

                    _unitOfWork.Candidate.Add(obj);
                    _unitOfWork.Save();
                    TempData["success"] = "Candidate Created Successfully";
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Log the exception here
                    Console.WriteLine("Error while creating Candidate: " + ex.Message); // Logging
                    TempData["errors"] = "Error while creating Candidate: " + ex.Message;
                }
            }
            TempData["errors"] = "Candidate Not Created";
            return View(obj);
        }




        //GET
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Update(int candidateId)
        {
            Candidate? obj = _unitOfWork.Candidate.Get(u => u.CandidateId == candidateId);

            //Villa? obj2 = _db.Villas.Find(villaId);

            //var VillaList = _db.Villas.Where(u => u.Price > 50 && u.Occupancy > 0).FirstOrDefault();

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }


        //POST
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Candidate obj)
        {
            if (ModelState.IsValid && obj.CandidateId > 0)
            {
                //Logo File Upload
                if (obj.Image != null)
                {
                    Console.WriteLine("ProfilePic Image is not null, proceeding with file upload."); // Logging

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(obj.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\CandidateProfilePics");
                    using var fileStream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);
                    obj.Image.CopyTo(fileStream);

                    obj.ProfilePicUrl = @"\images\CandidateProfilePics\" + fileName;
                }
                else
                {
                    Console.WriteLine("ProfilePic Image is null, using existing ProfilePic URL."); // Logging
                }

                _unitOfWork.Candidate.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Candidate Updated Successfully";
                return RedirectToAction(nameof(Index));
            }
            TempData["errors"] = "Candidate Not Updated";
            return View(obj);
        }







        //GET DELETE
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Delete(int candidateId)
        {
            Candidate? obj = _unitOfWork.Candidate.Get(u => u.CandidateId == candidateId);

            //Villa? obj2 = _db.Villas.Find(villaId);

            //var VillaList = _db.Villas.Where(u => u.Price > 50 && u.Occupancy > 0).FirstOrDefault();

            if (obj is null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(obj);
        }





        //POST DELETE
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult Delete(Candidate obj)
        {
            Candidate? objFromDb = _unitOfWork.Candidate.Get(u => u.CandidateId == obj.CandidateId);

            if (objFromDb is not null)
            {
                _unitOfWork.Candidate.Remove(objFromDb);
                _unitOfWork.Save();
                TempData["success"] = "Candidate Deleted Successfully";
                //return RedirectToAction("Index"); //Magic Strings
                return RedirectToAction(nameof(Index));
            }

            TempData["erros"] = "Candidate Not Deleted";
            return View(obj);

        }







    }
 
}

JobLandin.Web/Controllers/JobController.cs
using JobLandin.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using JobLandin.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using JobLandin.Web.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using JobLandin.Application.Common.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace JobLandin.Web.Controllers
{
    public class JobController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;

        private readonly ILogger<JobController> _logger;

        public JobController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager,
            ILogger<JobController> logger)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var jobs = _unitOfWork.Job.GetAll(includeProperties: "Company");

            if (User.IsInRole(SD.Role_Company))
            {
                var userId = _userManager.GetUserId(User);
                var company = await _unitOfWork.Company.GetFirstOrDefaultAsync(c => c.UserId == userId);
                if (company != null)
                {
                    ViewBag.CompanyId = company.CompanyId;
                }
            }

            return View(jobs);
        }


        //GET: Job/Create
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Company)]
        public IActionResult Create()
        {
            JobVM jobVM = new()
            {
                CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
                {
                    Text = u.CompanyName,
                    Value = u.CompanyId.ToString()
                })
            };

            return View(jobVM);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Company)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobVM obj)
        {
            if (User.IsInRole(SD.Role_Company))
            {
                var userId = _userManager.GetUserId(User);
                _logger.LogInformation($"User ID: {userId}");

                var company = await _unitOfWork.Company.GetFirstOrDefaultAsync(c => c.UserId == userId);
                _logger.LogInformation($"Company: {company}");

                if (company == null)
                {
                    return NotFound("Company not found for the current user.");
                }

                if (ModelState.IsValid)
                {
                    obj.Job.CompanyId = company.CompanyId;
                    _unitOfWork.Job.Add(obj.Job);
                    _unitOfWork.Save();
                    TempData["success"] = "The Job Offer has been created successfully.";
                    return RedirectToAction(nameof(Index));
                }
            }

            if (ModelState.IsValid)
            {
                _unitOfWork.Job.Add(obj.Job);
                _unitOfWork.Save();
                TempData["success"] = "The Job Offer has been created successfully.";
                return RedirectToAction(nameof(Index));
            }

            _logger.LogInformation(
                $"Model state is not valid. Errors: {string.Join(", ", ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage))}");

            obj.CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
            {
                Text = u.CompanyName,
                Value = u.CompanyId.ToString()
            });

            return View(obj);
        }


        //GET UPDATE

//GET
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Company)]
        public async Task<IActionResult> Update(int jobId)
        {
            var job = _unitOfWork.Job.Get(u => u.Id == jobId);
            if (job == null)
            {
                return RedirectToAction("Error", "Home");
            }

            if (User.IsInRole(SD.Role_Company))
            {
                var userId = _userManager.GetUserId(User);
                var company = await _unitOfWork.Company.GetFirstOrDefaultAsync(c => c.UserId == userId);
                if (company == null || job.CompanyId != company.CompanyId)
                    if (!User.IsInRole(SD.Role_Admin))
                    {
                        {
                            return Forbid(); // or any other action you want to take
                        }
                    }
            }

            JobVM jobVm = new()
            {
                CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
                {
                    Text = u.CompanyName,
                    Value = u.CompanyId.ToString()
                }),
                Job = job
            };

            return View(jobVm);
        }


        //POST UPDATE
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Company)]
        [ValidateAntiForgeryToken]
        public IActionResult Update(JobVM jobVM)
        {
            if (ModelState.IsValid)
            {
                // Ensure that the Job's Id is set correctly
                if (jobVM.Job.Id <= 0)
                {
                    TempData["error"] = "Invalid Job Id.";
                    return View(jobVM);
                }

                _unitOfWork.Job.Update(jobVM.Job);
                _unitOfWork.Save();
                TempData["success"] = "The Job Offer has been updated successfully.";
                return RedirectToAction(nameof(Index));
            }

            jobVM.CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
            {
                Text = u.CompanyName,
                Value = u.CompanyId.ToString()
            });

            return View(jobVM);
        }


        //GET DELETE
        //GET
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Company)]
        public IActionResult Delete(int jobId)
        {
            JobVM jobVM = new()
            {
                CompanyList = _unitOfWork.Company.GetAll().Select(u => new SelectListItem
                {
                    Text = u.CompanyName,
                    Value = u.CompanyId.ToString()
                }),
                Job = _unitOfWork.Job.Get(u => u.Id == jobId)
            };

            if (jobVM.Job is null)
            {
                return RedirectToAction("Error", "Home");
            }

            return View(jobVM);
        }


        //POST DELETE
        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Company)]
        public IActionResult Delete(JobVM jobVm)
        {
            Job? objFromDb = _unitOfWork.Job.Get(_ => _.Id == jobVm.Job.Id);

            if (objFromDb is not null)
            {
                _unitOfWork.Job.Remove(objFromDb);
                _unitOfWork.Save();

                TempData["success"] = "The Job Offer has been deleted successfully.";

                return RedirectToAction(nameof(Index));
            }

            TempData["error"] = "The Job Offer could not be deleted.";
            return View(jobVm);
        }
    }
}

JobLandin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JobLandin.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/css/bootstrap.min.css" integrity="sha512-jnSuA4Ss2PkkikSOLtYs8BlYIeeIK1h99ty4YfvRPAlzr377vr3CXDb7sb7eEEBYjDtcYj+AjBH3FLv5uSJuXg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JobLandin.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JobLandin.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Job" asp-action="Index">Jobs List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Company" asp-action="Index">Companies List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Candidate" asp-action="Index">Candidates List</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
            <div class="p-2 border rounded mr-5 px-2">
                <div class="form-check form-switch" id="btnSwitch">
                    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault">
                    <i class="bi bi-yin-yang bi-5"></i>
                </div>
            </div>
            <div class="p-2 mr-5 px-2">

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - JobLandin.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script type="text/javascript">
        window.addEventListener('DOMContentLoaded', (event) => {
            // On page load, set the theme from localStorage
            var theme = localStorage.getItem('theme');
            if (theme) {
                document.documentElement.setAttribute('data-bs-theme', theme);
            }
        });

        document.getElementById('btnSwitch').addEventListener('click', () => {
            // On switch click, toggle the theme and save it in localStorage
            var theme = document.documentElement.getAttribute('data-bs-theme') === 'dark' ? 'light' : 'dark';
            document.documentElement.setAttribute('data-bs-theme', theme);
            localStorage.setItem('theme', theme);
        });

    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>